Parse alt column structure
juliangruber/parse-apache-directory-index pull request #3
Opened 2016-09-21 15:09 UTC by eschwartz

Parse header row, to determine column structure

before, we were assuming that the columns were in a certain order.
However, this may not always be the case
- see http://ftp.wpc.ncep.noaa.gov/, for example,
  which is missing an `Icon` row

The parsing script is more flexible now --
 it parses the header row first, to determine the column ordering,
 and then parses each column using that same ordering

2016-09-21 15:53 UTC, juliangruber commented on test/fixture/apache-index.html
> +    <td align="right"> 5.4M</td>
why did you modify those?

2016-09-21 15:54 UTC, juliangruber requested changes
..the rest looks good to me!

2016-09-21 19:29 UTC, eschwartz commented on test/fixture/apache-index.html
> +    <td align="right"> 5.4M</td>
If I remember correctly, I removed the `size` field from `folderB/` (folders shouldn't have a size). But I still wanted to test that we are parsing `M` (megabyte) values correctly.

2016-11-01 19:44 UTC, eschwartz commented
can this be merged in?

2016-11-01 22:00 UTC, juliangruber commented
modifications to existing tests are always dangerous as they might shadow unintentional breaking changes. i'd rather we add another fixture instead. then i'll merge and release :)

2016-11-02 14:33 UTC, eschwartz commented
I reverted the fixture changes, and also fixed some linter errors that were causing `npm test` to fail.

2016-11-02 14:44 UTC, juliangruber approved these changes

2016-11-02 14:44 UTC, merged

2016-11-02 14:45 UTC, juliangruber commented
awesome! thank you for your work and patience :) released as 1.2.0